/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PhotoListItemDto"][];
                        "application/json": components["schemas"]["PhotoListItemDto"][];
                        "text/json": components["schemas"]["PhotoListItemDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PhotoDeleteRequestDto"];
                    "text/json": components["schemas"]["PhotoDeleteRequestDto"];
                    "application/*+json": components["schemas"]["PhotoDeleteRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PhotoDeleteResultDto"];
                        "application/json": components["schemas"]["PhotoDeleteResultDto"];
                        "text/json": components["schemas"]["PhotoDeleteResultDto"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterDto"];
                    "text/json": components["schemas"]["RegisterDto"];
                    "application/*+json": components["schemas"]["RegisterDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponseDto"];
                        "application/json": components["schemas"]["AuthResponseDto"];
                        "text/json": components["schemas"]["AuthResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginDto"];
                    "text/json": components["schemas"]["LoginDto"];
                    "application/*+json": components["schemas"]["LoginDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponseDto"];
                        "application/json": components["schemas"]["AuthResponseDto"];
                        "text/json": components["schemas"]["AuthResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Coffees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CoffeeResponseDto"][];
                        "application/json": components["schemas"]["CoffeeResponseDto"][];
                        "text/json": components["schemas"]["CoffeeResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CoffeeCreateDto"];
                    "text/json": components["schemas"]["CoffeeCreateDto"];
                    "application/*+json": components["schemas"]["CoffeeCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CoffeeResponseDto"];
                        "application/json": components["schemas"]["CoffeeResponseDto"];
                        "text/json": components["schemas"]["CoffeeResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Coffees/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CoffeeResponseDto"];
                        "application/json": components["schemas"]["CoffeeResponseDto"];
                        "text/json": components["schemas"]["CoffeeResponseDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CoffeeUpdateDto"];
                    "text/json": components["schemas"]["CoffeeUpdateDto"];
                    "application/*+json": components["schemas"]["CoffeeUpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Coffees/{id}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CoffeeResponseDto"];
                        "application/json": components["schemas"]["CoffeeResponseDto"];
                        "text/json": components["schemas"]["CoffeeResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ConfigDto"];
                        "application/json": components["schemas"]["ConfigDto"];
                        "text/json": components["schemas"]["ConfigDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flavor-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FlavorTagDto"][];
                        "application/json": components["schemas"]["FlavorTagDto"][];
                        "text/json": components["schemas"]["FlavorTagDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coffees/{coffeeId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    coffeeId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ReviewResponseDto"][];
                        "application/json": components["schemas"]["ReviewResponseDto"][];
                        "text/json": components["schemas"]["ReviewResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    coffeeId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReviewCreateDto"];
                    "text/json": components["schemas"]["ReviewCreateDto"];
                    "application/*+json": components["schemas"]["ReviewCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ReviewResponseDto"];
                        "application/json": components["schemas"]["ReviewResponseDto"];
                        "text/json": components["schemas"]["ReviewResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coffees/{coffeeId}/reviews/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    coffeeId: number;
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ReviewResponseDto"];
                        "application/json": components["schemas"]["ReviewResponseDto"];
                        "text/json": components["schemas"]["ReviewResponseDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    coffeeId: number;
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReviewUpdateDto"];
                    "text/json": components["schemas"]["ReviewUpdateDto"];
                    "application/*+json": components["schemas"]["ReviewUpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ReviewResponseDto"];
                        "application/json": components["schemas"]["ReviewResponseDto"];
                        "text/json": components["schemas"]["ReviewResponseDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    coffeeId: number;
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coffees/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ScanResponseDto"];
                        "application/json": components["schemas"]["ScanResponseDto"];
                        "text/json": components["schemas"]["ScanResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthResponseDto: {
            token: string;
            /** Format: date-time */
            expiresAt: string;
            userId: string;
            displayName: null | string;
            isAdmin: boolean;
        };
        CoffeeCreateDto: {
            name: string;
            roaster: string;
            origin: string;
            roastLevel: null | components["schemas"]["RoastLevel"];
            /** Format: double */
            price: number | string;
            /** Format: date */
            dateBought: string;
            shopName: null | string;
            purchaseUrl: null | string;
        };
        CoffeeResponseDto: {
            /** Format: int32 */
            id: number | string;
            name: string;
            roaster: string;
            origin: string;
            roastLevel: components["schemas"]["RoastLevel"];
            /** Format: double */
            price: number | string;
            /** Format: date */
            dateBought: string;
            photoPath: null | string;
            shopName: null | string;
            purchaseUrl: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: double */
            averageRating: null | number | string;
            /** Format: int32 */
            reviewCount: number | string;
            flavorTags: string[];
        };
        CoffeeUpdateDto: {
            name: string;
            roaster: string;
            origin: string;
            roastLevel: null | components["schemas"]["RoastLevel"];
            /** Format: double */
            price: number | string;
            /** Format: date */
            dateBought: string;
            shopName: null | string;
            purchaseUrl: null | string;
        };
        ConfigDto: {
            registrationEnabled: boolean;
        };
        FlavorTagDto: {
            /** Format: int32 */
            id: number | string;
            name: string;
        };
        /** Format: binary */
        IFormFile: string;
        LoginDto: {
            email: string;
            password: string;
        };
        PhotoDeleteRequestDto: {
            paths: string[];
        };
        PhotoDeleteResultDto: {
            /** Format: int32 */
            deleted: number | string;
            /** Format: int32 */
            skipped: number | string;
        };
        PhotoListItemDto: {
            path: string;
            used: boolean;
        };
        RegisterDto: {
            email: string;
            password: string;
            displayName: string;
        };
        ReviewCreateDto: {
            /** Format: int32 */
            rating: number | string;
            tastingNotes: null | string;
            brewMethod: null | string;
            grind: null | string;
            ratio: null | string;
            tagIds: null | (number | string)[];
            stage?: null | string;
        };
        ReviewResponseDto: {
            /** Format: int32 */
            id: number | string;
            /** Format: int32 */
            coffeeId: number | string;
            userId: string;
            /** Format: int32 */
            rating: number | string;
            stage: null | string;
            tastingNotes: null | string;
            brewMethod: null | string;
            grind: null | string;
            ratio: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: null | string;
            tags: components["schemas"]["FlavorTagDto"][];
        };
        ReviewUpdateDto: {
            /** Format: int32 */
            rating: number | string;
            tastingNotes: null | string;
            brewMethod: null | string;
            grind: null | string;
            ratio: null | string;
            tagIds: null | (number | string)[];
            stage?: null | string;
        };
        /** @enum {unknown} */
        RoastLevel: "Light" | "Medium" | "Dark";
        ScannedCoffeeDto: {
            name: null | string;
            roaster: null | string;
            origin: null | string;
            roastLevel: null | string;
            weight: null | string;
        };
        ScanResponseDto: {
            rawText: string;
            parsed: components["schemas"]["ScannedCoffeeDto"];
            photoPath: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
